# Note that ci_config_spec.rb has tests for this file's contents
# some of the defines were guessed from
#   https://en.wikipedia.org/wiki/List_of_Arduino_boards_and_compatible_systems

packages:
  arduino:avr:
    url: https://downloads.arduino.cc/packages/package_index.json
  arduino:sam:
    url: https://downloads.arduino.cc/packages/package_index.json
  arduino:samd:
    url: https://downloads.arduino.cc/packages/package_index.json
  arduino:megaavr:
    url: https://downloads.arduino.cc/packages/package_index.json
  esp8266:esp8266:
    url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
  adafruit:avr:
    url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
  adafruit:samd:
    url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
  esp32:esp32:
    url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

platforms:

  uno:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATmega328P__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_UNO
      warnings:
      flags:
  due:
    board: arduino:sam:arduino_due_x
    package: arduino:sam
    gcc:
      features:
      defines:
        - __SAM3X8E__
        - ARDUINO_ARCH_SAM
        - ARDUINO_SAM_DUE
        - NUM_SERIAL_PORTS=4
      warnings:
      flags:
  zero:
    board: arduino:samd:arduino_zero_native
    package: arduino:samd
    gcc:
      features:
      defines:
        - __SAMD21G18A__
        - ARDUINO_ARCH_SAMD
        - ARDUINO_SAMD_ZERO
        # This also has SerialUSB, which is not included here.
        - NUM_SERIAL_PORTS=2
      warnings:
      flags:
  nano_every:
    board: arduino:megaavr:nona4809
    package: arduino:megaavr
    gcc:
      features:
      defines:
        - MILLIS_USE_TIMERB3
        - NO_EXTERNAL_I2C_PULLUP
        - AVR_NANO_4809_328MODE
      warnings:
      flags:
  esp32:
    board: esp32:esp32:featheresp32:FlashFreq=80
    package: esp32:esp32
    gcc:
      features:
      defines:
        - ESP32
        - ARDUINO_ARCH_ESP32
        - ARDUINO_FEATHER_ESP32
        - NUM_SERIAL_PORTS=3
      warnings:
      flags:
  esp8266:
    board: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
    package: esp8266:esp8266
    gcc:
      features:
      defines:
        - ESP8266
        - ARDUINO_ARCH_ESP8266
        - ARDUINO_ESP8266_ESP12
        - NUM_SERIAL_PORTS=2
      warnings:
      flags:
  leonardo:
    board: arduino:avr:leonardo
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATmega32U4__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_LEONARDO
      warnings:
      flags:
  trinket:
    board: adafruit:avr:trinket5
    package: adafruit:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATtiny85__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_TRINKET5
      warnings:
      flags:
  gemma:
    board: arduino:avr:gemma
    package: adafruit:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATtiny85__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_GEMMA
      warnings:
      flags:
  m4:
    board: adafruit:samd:adafruit_metro_m4
    package: adafruit:samd
    gcc:
      features:
      defines:
        - __SAMD51__
        - __SAMD51J19A__
        - ARDUINO_ARCH_SAMD
        - ARDUINO_METRO_M4
        # Serial is actually USB virtual serial, not HardwareSerial
        - NUM_SERIAL_PORTS=2
      warnings:
      flags:
  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATmega2560__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_MEGA2560
      warnings:
      flags:
  cplayClassic:
    board: arduino:avr:circuitplay32u4cat
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATmega32U4__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_CIRCUITPLAY
      warnings:
      flags:
  cplayExpress:
    board: arduino:samd:adafruit_circuitplayground_m0
    package: arduino:samd
    gcc:
      features:
      defines:
        - __SAMD21G18A__
        - ARDUINO_ARCH_SAMD
        - ARDUINO_SAMD_CIRCUITPLAYGROUND_EXPRESS
        # Serial is actually an alias of SerialUSB, not a HardwareSerial
        - NUM_SERIAL_PORTS=2
      warnings:
      flags:


compile:
  libraries: ~
  platforms:
    - uno
    - due
    - zero
    - leonardo
    - m4
    - esp32
    - esp8266
    - mega2560

unittest:
  compilers:
    - g++
  libraries: ~
  platforms:
    - uno
    - due
    - zero
    - leonardo
