# Note that ci_config_spec.rb has tests for this file's contents
# some of the defines were guessed from
#   https://en.wikipedia.org/wiki/List_of_Arduino_boards_and_compatible_systems

packages:
  # arduino:xxx are builtin, we don't need to include them here
  esp8266:esp8266:
    url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
  adafruit:avr:
    url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
  adafruit:samd:
    url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
  esp32:esp32:
    url: https://dl.espressif.com/dl/package_esp32_index.json

platforms:
  
  nano_v2:
    board: arduino:avr:nano
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega168__
      warnings:
      flags:
  nano_v3: &nano_p
    board: arduino:avr:nano
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega328__
      warnings:
      flags:
  nano: *nano_p
  uno:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega328P__
      warnings:
      flags:
  due:
    board: arduino:sam:arduino_due_x
    package: arduino:sam
    gcc:
      features:
      defines:
        # The due should use the ATSAM3X8E; however, that component does not seem
        # to be defined for the Godmode tests/components
        # The next closest part would be the AVR_ATmega2560 as both boards
        # use the mega form factor
        #- __ATSAM3X8E__
        - __AVR_ATmega2560__
        #- __AVR_ATmega328__
      warnings:
      flags:
  zero:
    board: arduino:samd:arduino_zero_native
    package: arduino:samd
    gcc:
      features:
      defines:
       - __SAMD21G18A__
       - ARDUINO_SAMD_ZERO
      warnings:
      flags:
  esp32:
    board: esp32:esp32:featheresp32:FlashFreq=80
    package: esp32:esp32
    gcc:
      features:
      defines:
      warnings:
      flags:
  esp8266:
    board: esp8266:esp8266:huzzah:FlashSize=4M3M,CpuFrequency=80
    package: esp8266:esp8266
    gcc:
      features:
      defines:
      warnings:
      flags:
  leonardo:
    board: arduino:avr:leonardo
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega32U4__
      warnings:
      flags:
  trinket:
    board: adafruit:avr:trinket5
    package: adafruit:avr
    gcc:
      features:
      defines:
      warnings:
      flags:
  gemma:
    board: arduino:avr:gemma
    package: adafruit:avr
    gcc:
      features:
      defines:
      warnings:
      flags:
  m4:
    board: adafruit:samd:adafruit_metro_m4
    package: adafruit:samd
    gcc:
      features:
      defines:
      warnings:
      flags:
  grand_central_m4:
    board: adafruit:samd:adafruit_grand_central_m4
    package: adafruit:samd
    gcc:
      features:
      defines:
      warnings:
      flags:
  mega1280:
    board: arduino:avr:mega:cpu=atmega1280
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega1280__
      warnings:
      flags:
  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega2560__
      warnings:
      flags:
  cplayClassic:
    board: arduino:avr:circuitplay32u4cat
    package: arduino:avr
    gcc:
      features:
      defines:
      warnings:
      flags:
  cplayExpress:
    board: arduino:samd:adafruit_circuitplayground_m0
    package: arduino:samd
    gcc:
      features:
      defines:
      warnings:
      flags:


compile:
  libraries: ~
  platforms:
    - uno
    - due
    - zero
    - leonardo
    - m4
    - esp32
    - esp8266
    - mega2560

unittest:
  compilers:
    - g++
  libraries: ~
  platforms:
    - uno
    - due
    - zero
    - leonardo
