AllCops:
  Exclude:
    - '*.gemspec'
    - 'spec/*.rb'
    - '**/generated_parser/*'
    - './vendor/**/*'
    - 'SampleProjects/**/vendor/**/*'

# TODO: stuff I actually want to fix
Style/RescueStandardError:
  Enabled: false

Security/Open:
  Enabled: false


# Extra lines for readability
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Configuration parameters: AllowForAlignment.
Layout/ExtraSpacing:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/CaseIndentation:
  EnforcedStyle: end

Metrics/LineLength:
  Description: Limit lines to 80 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 130

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Enabled: false
  Max: 400

Metrics/AbcSize:
  Enabled: false
  Max: 50

Metrics/MethodLength:
  Enabled: false
  Max: 50

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

Style/BlockComments:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

# if you find "a == 3" readable and "3 == a" 'unreadable', do not contribute to this project.
Style/YodaCondition:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 1
Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 11

# Offense count: 1
Metrics/PerceivedComplexity:
  Enabled: false
  Max: 14

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# because apostrophes
Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# because if the robot can comment better than me then
# it might as well learn to write the code for me
Style/CommentAnnotation:
  Enabled: false
