# This is the name of the workflow, visible on GitHub UI
name: linux

on: [push, pull_request]

jobs:
  "unittest_lint_sampleproject":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Check style, functionality, and usage
        run: |
          g++ -v
          bundle install
          bundle exec rubocop --version
          bundle exec rubocop -D .
          bundle exec rspec --backtrace
          cd SampleProjects/TestSomething
          bundle install
          bundle exec arduino_ci.rb

  NetworkLib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Test NetworkLib from scratch
        run: |
          g++ -v
          cd SampleProjects/NetworkLib
          bundle install
          bundle exec ensure_arduino_installation.rb
          sh ./scripts/install.sh
          bundle exec arduino_ci.rb
