# This is the name of the workflow, visible on GitHub UI
name: linux

on: [push, pull_request]

jobs:
  "BusIO_with_dependencies":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Check usage - Test BusIO from scratch
        run: |
          g++ -v
          cd SampleProjects/BusIO
          bundle install
          bundle exec ensure_arduino_installation.rb
          bundle exec arduino_ci.rb

  "rubocop":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Check style
        run: |
          g++ -v
          bundle install
          bundle exec rubocop --version
          bundle exec rubocop -D .

  "rspec-linux":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Check functionality
        run: |
          g++ -v
          bundle install
          bundle exec rspec

  "TestSomething":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Check usage - TestSomething
        run: |
          g++ -v
          bundle install
          cd SampleProjects/TestSomething
          bundle install
          bundle exec arduino_ci.rb --help
          bundle exec arduino_ci.rb

  NetworkLib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Check usage - Test NetworkLib from scratch
        run: |
          g++ -v
          cd SampleProjects/NetworkLib
          bundle install
          bundle exec ensure_arduino_installation.rb
          sh ./scripts/install.sh
          bundle exec arduino_ci.rb

  SharedLibrary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Check usage - Test SharedLibrary should fail
        run: ./SampleProjects/SharedLibrary/test.sh

  Makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Check usage - Demo Makefile
        run: ./SampleProjects/Makefile/test.sh
