# This is the name of the workflow, visible on GitHub UI
name: linux

# Run on a Push or a Pull Request
on: [push, pull_request]

jobs:
  rubocop: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6

      # Install and run Arduino CI tests for rubocop
      - name: Build and Execute
        run: |
          g++ -v
          bundle install
          bundle exec rubocop --version
          bundle exec rubocop -D .
          bundle exec rspec --backtrace

  TestSomething: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6

      # Install and run Arduino CI tests for TestSomething
      - name: Build and Execute
        run: |
          g++ -v
          bundle install
          cd SampleProjects/TestSomething
          bundle install
          bundle exec arduino_ci.rb

  NetworkLib: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6

      # Install and run Arduino CI tests for NetworkLib
      - name: Build and Execute
        run: |
          g++ -v
          bundle install
          cd SampleProjects/NetworkLib
          ./scripts/install.sh
          bundle install
          bundle exec arduino_ci.rb
