# This is the name of the workflow, visible on GitHub UI
name: spelling

on: [push, pull_request]

jobs:
  uses: codespell-project/actions-codespell@master
  with:
    check_filenames: true
    ignore_words_file: .codespellignore
